### ISSUE TITLE
Doesnt Work

### ISSUE THREAD

**Issue by ShadowRacerX8** [Da532/Innocent-bot#13] opened 2019-01-19 21:38 UTC
I dont know what I am doing wrong. All dependencies are installed properly. I am imputting my token, prefix and rename_to value. Keeps saying invalid syntax... If you can help me that would be great!

**Comment by maxichrome** [comment] 2019-02-08 03:52
Hi @ShadowRacerX8, there will be an update for Innocent coming out soon. The current version is unsupported. Please watch the repository and you'll be notified once the next release comes out. Thank you!

**Comment by maxichrome** [comment] 2019-02-27 00:51
Closing this as a duplicate of #7. If you think this is a different problem, please reopen this issue.

**Closed as completed by maxichrome** 2019-02-27 00:51 UTC
Labels: bug, duplicate
